name       : dolphin-emu
version    : 5.0
release    : 2
source     :
    - https://github.com/dolphin-emu/dolphin/archive/5.0.tar.gz : 62c4602055767ab314ff50a3b94ea57f792832aa1629e6b1117ebce10518dc0b
license    : GPL-2.0
component  : games.emulator
summary    : GameCube / Wii emulator.
description: |
    GameCube / Wii emulator, allowing you to play games for these two platforms on PC.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(bluez)
    - pkgconfig(gl)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libenet)
    - pkgconfig(libevdev)
    - pkgconfig(libpulse)
    - pkgconfig(libusb-1.0)
    - pkgconfig(openal)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(sdl2)
    - pkgconfig(sfml-all)
    - pkgconfig(soundtouch)
    - pkgconfig(xi)
    - gtest-devel
    - llvm-devel
    - lzo-devel
    - mbedtls-devel
    - miniupnpc-devel
    - wxwidgets-devel
setup      : |
    %cmake -DUSE_SHARED_ENET=TRUE \
           -DUSE_SHARED_GTEST=TRUE .
build      : |
    %make
install    : |
    %make_install
