name       : dolphin-emu
version    : 5.0
release    : 21
source     :
    - git|https://github.com/dolphin-emu/dolphin.git : 48862850ca1deb5a5053b0931f7eeaf14b46e2bc
license    : GPL-2.0-or-later
component  : games.emulator
summary    : GameCube / Wii emulator
description: |
    GameCube / Wii emulator, allowing you to play games for these two platforms on PC.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(alsa)
    - pkgconfig(bluez)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libenet)
    - pkgconfig(libevdev)
    - pkgconfig(libpulse)
    - pkgconfig(libusb-1.0)
    - pkgconfig(openal)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(sdl2)
    - pkgconfig(sfml-all)
    - pkgconfig(soundtouch)
    - pkgconfig(xi)
    - pkgconfig(xrandr)
    - gtest-devel
    - llvm-devel
    - lzo-devel
    - mbedtls-devel
    - miniupnpc-devel
setup      : |
    %cmake -DENABLE_QT=TRUE \
           -DUSE_SHARED_ENET=TRUE \
           -DUSE_SHARED_GTEST=TRUE .
build      : |
    %make
install    : |
    %make_install

    # Install udev rule
    install -Dm00644 Data/51-usb-device.rules $installdir/%libdir%/udev/rules.d/51-usb-device.rules
